# inventory/hosts.ini
# Add your LXC containers and VMs here.
# The playbook auto-detects the package manager on each host.

[lxcs]
lxc-prometheus ansible_port=22 ansible_host=192.168.0.248 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
lxc-grafana ansible_port=22 ansible_host=192.168.0.247 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
lxc-proxexport ansible_port=22 ansible_host=192.168.0.246 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
lxc-optiping ansible_port=22 ansible_host=192.168.0.244 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa

[vms]
vm-debian-media-server    ansible_port=22 ansible_host=192.168.0.230 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
vm-debian-remote-desktop    ansible_port=22 ansible_host=192.168.0.245 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
vm-alpine-gitea-dev.server.wow    ansible_port=22 ansible_host=192.168.0.249 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
vm-debian-ut99-server    ansible_port=22 ansible_host=192.168.0.108 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
vm-debian-dev.server.wow    ansible_port=22 ansible_host=192.168.0.250 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
vm-debian-navidrome-bean    ansible_port=22 ansible_host=192.168.0.163 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
vm-debian-mc-server    ansible_port=22 ansible_host=192.168.0.142 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
vm-alpine-mysql-bckp-dev.wow.server    ansible_port=22 ansible_host=192.168.0.251 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa
vm-debian-ut2004-server    ansible_port=22 ansible_host=192.168.0.201 ansible_user=ansibleuser ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:children]
lxcs
vms
